language: python
python:
- '3.6'
install:
- python setup.py install
script:
- python -m unittest pygef/tests.py
- python -m unittest pygef/robertson/tests.py
- python -m unittest pygef/been_jeffrey/tests.py

