name: Release

on:
  push:
    tags: ['*']

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: release

    # Mandatory permission for trusted publishing to PyPi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install setuptools build

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
